* 2020-05-10

** La limite pour la tranche d'âge supérieur est à 65 ans au lieu de 70 ans

Les valeurs possibles pour la variable =age_range= sont désormais
=inf_15=, =from_15_to_49=, =from_50_to_64= et =sup_65=.

Voir le [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/blob/master/schema.json][schéma de données]] mis à jour.

** Tous les messages d'orientation FIN2 ont été remplacées par ceux de la FIN6

Le message d'orientation =FIN2= était :

: Votre situation peut relever d’un COVID 19 qu’il faut surveiller. Si
: de nouveaux symptômes apparaissent, refaites le test ou consultez
: votre médecin. Nous vous conseillons de rester à votre domicile.

Tous ces messages sont désormais remplacés par celui de la =FIN6= :

: Votre situation peut relever d’un COVID 19. Demandez une
: téléconsultation ou un médecin généraliste ou une visite à domicile
: (SOS médecins, etc.) En attendant et pour casser les chaînes de
: transmission, nous vous conseillons de vous isoler et de respecter les
: gestes barrières pour protéger vos proches.

L'orientation =FIN2= disparaît donc de l'algorithme d'orientation.

** Les messages d'orientation pour FIN3, FIN4, FIN6, FIN7 ont été modifiés

Pour tous ces messages, la phrase suivante à été ajoutée à la fin :

: En attendant et pour casser les chaînes de transmission, nous vous
: conseillons de vous isoler et de respecter les gestes barrières pour
: protéger vos proches.

* 2020-04-29

** Ajout d'un identifiant unique

Le tableau des données du fichier =implementation.org= contient une
nouvelle ligne pour l'ajout d'un identifiant unique, optionnel.

Vous reporter au [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/][dépôt du schéma de données]] pour les détails.

** Nouvelles valeurs acceptables pour la variable "orientation"

 - less_15
 - home_surveillance
 - consultation_surveillance_1
 - consultation_surveillance_2
 - SAMU
 - consultation_surveillance_3
 - consultation_surveillance_4
 - surveillance

* 2020-04-17

** L'arbre de décision a été corrigé pour les 4ème et 5ème clauses

La 4ème clause disait:

: "IF fièvre OR (diarrhée OR (toux AND douleurs) OR (toux AND anosmie))"

Elle dit désormais:

: IF fièvre OR (diarrhée OR (toux AND douleurs) OR (toux AND anosmie) OR (douleurs AND anosmie))

La 5ème clause disait:

: IF toux OR douleurs OR anosmie
 
Elle dit désormais:

: IF toux XOR douleurs XOR anosmie

Voir le [[file:pseudo-code.org][pseudo-code]].

** Une seule question pour la fièvre

La fièvre était demandée en deux temps : d'abord une question pour
savoir si le répondant avait de la fièvre, une autre pour demander la
température.  Il n'y a désormais qu'une seule question, celle sur la
température.

En conséquence, les solutions ne doivent plus envoyer de valeur ~fever~
mais seulement ~fever_algo~ et ~temperature_cat~ : voir [[file:implementation.org][l'implémentation]].

À noter que si le répondant indique "Je ne sais pas", cela est
considéré ensuite dans l'algorithme comme indiquant de la fièvre.

** Clarification sur la question du code postal

La question sur le code postal a été précisée : il s'agit de demander
le code postal du lieu de résidence actuel, pas du domicile.

** Ajout d'un fichier ChangeLog.org

Tous les changements sur l'algorithme ayant un impact potentiel sur
les implémentations seront désormais notés dans ce fichier.
