* 2020-06-09

** Correction de l'algorithme

Une [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/pull/49][correction]] a été apportée à l'une des branches de l'algorithme.

** Mise à jour des questions

Plusieurs questions ont été reformulées :

- /Avez-vous une toux ou votre toux habituelle s’est-elle modifiée ces derniers jours ?/
- /Avez-vous noté une perte ou une forte diminution de votre goût ou de votre odorat ces derniers jours ?/
- /Avez-vous un mal de gorge ou des douleurs musculaires ou des courbatures inhabituelles ou des maux de tête inhabituels ces derniers jours ?/
  - Si la réponse est OUI, afficher /Si vous avez des maux de tête qui ne disparaissent pas après la prise de médicaments anti-douleurs (dont paracétamol) et que vous décririez comme intolérables : Appelez le 15./
- /Êtes-vous une femme enceinte au 3ème trimestre de votre grossesse  ?/
- /Avez-vous des antécédents de maladie cardiovasculaire : hypertension artérielle compliquée (avec complications cardiaques, rénales), accident vasculaire cérébral, maladie coronaire (infarctus), chirurgie cardiaque, insuffisance cardiaque avec essoufflement au moindre effort ?/
- /Avez-vous une cirrhose ?/  [À la place de la question sur la maladie du foi.]
- /Avez-vous un diabète mal équilibré ou avec des complications (yeux, reins) ?/
- /Avez-vous une insuffisance rénale chronique avec besoin de faire de la dialyse ?/
- /Avez-vous un cancer évolutif sous traitement (hors hormonothérapie) ?/
- /Avez-vous une maladie respiratoire chronique (bronchopneumopathie obstructive, asthme sévère, fibrose pulmonaire, syndrome d’apnées du sommeil, mucoviscidose) ou êtes-vous suivi par un pneumologue ?/
- /Avez-vous une immunodépression, par exemple : médicamenteuse (chimiothérapie anti cancéreuse, traitement immunosuppresseur, biothérapie et/ou corticothérapie à dose immunosuppressive depuis plus de 15 jours) ; infection à VIH non contrôlée ou avec des CD4 <200/mm3 ; consécutive à une greffe d'organe solide ou de cellules souches hématopoïétiques ; liée à une hémopathie maligne en cours de traitement ?/

Une question a été ajoutée :

- /Avez-vous une drépanocytose homozygote (forme majeure) ou j’ai bénéficié d’une splénectomie (ablation de la rate) à cause de la drépanocytose ?/

Une question a été supprimée :

- /Prenez-vous un traitement immunosuppresseur ?/

** Mise à jour des variables exigées

- La variable =sickle_cell= correspondant à la question sur la
  drépanocytose a été ajoutée dans la liste des données exigées.

- Les variables =immunosuppressant_drug= et =immunosuppressant_drug_algo=
  ne sont plus exigées, car la question /Prenez-vous un traitement
  immunosuppresseur ?/ a été supprimée.

** Harmonisation en « Covid-19 »

L'appellation « Covid-19 » est désormais utilisée partout dans la documentation.

* 2020-05-10

** La limite pour la tranche d'âge supérieur est à 65 ans au lieu de 70 ans

Les valeurs possibles pour la variable =age_range= sont désormais
=inf_15=, =from_15_to_49=, =from_50_to_64= et =sup_65=.

Voir le [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/blob/master/schema.json][schéma de données]] mis à jour.

** Tous les messages d'orientation FIN2 ont été remplacées par ceux de la FIN6

Le message d'orientation =FIN2= était :

: Votre situation peut relever d’un COVID 19 qu’il faut surveiller. Si
: de nouveaux symptômes apparaissent, refaites le test ou consultez
: votre médecin. Nous vous conseillons de rester à votre domicile.

Tous ces messages sont désormais remplacés par celui de la =FIN6= :

: Votre situation peut relever d’un COVID 19. Demandez une
: téléconsultation ou un médecin généraliste ou une visite à domicile
: (SOS médecins, etc.) En attendant et pour casser les chaînes de
: transmission, nous vous conseillons de vous isoler et de respecter les
: gestes barrières pour protéger vos proches.

L'orientation =FIN2= disparaît donc de l'algorithme d'orientation.

** Les messages d'orientation pour FIN3, FIN4, FIN6, FIN7 ont été modifiés

Pour tous ces messages, la phrase suivante à été ajoutée à la fin :

: En attendant et pour casser les chaînes de transmission, nous vous
: conseillons de vous isoler et de respecter les gestes barrières pour
: protéger vos proches.

* 2020-04-29

** Ajout d'un identifiant unique

Le tableau des données du fichier =implementation.org= contient une
nouvelle ligne pour l'ajout d'un identifiant unique, optionnel.

Vous reporter au [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation-check/][dépôt du schéma de données]] pour les détails.

** Nouvelles valeurs acceptables pour la variable "orientation"

 - less_15
 - home_surveillance
 - consultation_surveillance_1
 - consultation_surveillance_2
 - SAMU
 - consultation_surveillance_3
 - consultation_surveillance_4
 - surveillance

* 2020-04-17

** L'arbre de décision a été corrigé pour les 4ème et 5ème clauses

La 4ème clause disait:

: "IF fièvre OR (diarrhée OR (toux AND douleurs) OR (toux AND anosmie))"

Elle dit désormais:

: IF fièvre OR (diarrhée OR (toux AND douleurs) OR (toux AND anosmie) OR (douleurs AND anosmie))

La 5ème clause disait:

: IF toux OR douleurs OR anosmie
 
Elle dit désormais:

: IF toux XOR douleurs XOR anosmie

Voir le [[file:pseudo-code.org][pseudo-code]].

** Une seule question pour la fièvre

La fièvre était demandée en deux temps : d'abord une question pour
savoir si le répondant avait de la fièvre, une autre pour demander la
température.  Il n'y a désormais qu'une seule question, celle sur la
température.

En conséquence, les solutions ne doivent plus envoyer de valeur ~fever~
mais seulement ~fever_algo~ et ~temperature_cat~ : voir [[file:implementation.org][l'implémentation]].

À noter que si le répondant indique "Je ne sais pas", cela est
considéré ensuite dans l'algorithme comme indiquant de la fièvre.

** Clarification sur la question du code postal

La question sur le code postal a été précisée : il s'agit de demander
le code postal du lieu de résidence actuel, pas du domicile.

** Ajout d'un fichier ChangeLog.org

Tous les changements sur l'algorithme ayant un impact potentiel sur
les implémentations seront désormais notés dans ce fichier.
