# Default locale for UI strings
locale: "fr"

# Customize UI strings
ui-strings:
  # display-help:         "Display help"
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # redo:                 "Redo"
  # ok:                   "Okay"
  # contact-intro:        "Contact: "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Allow users to send you emails with the summary?
mail-to:

# Display help along with questions by default?
display-help: true

# Display score along with the results?
display-score: true

init-scores:
  fievre:
    display: "Fièvre"
    value: 0
    result: "De la fièvre"
  toux:
    display: "Toux"
    value: 0
    result: "De la toux"
  courbatures:
    display: "Courbatures"
    value: 0
    result: "Des courbatures"
  mal_de_gorge:
    display: "Mal de gorge"
    value: 0
    result: "Mal de gorge"
  diarrhees:
    display: "Diarrhées"
    value: 0
    result: "Diarrhées"
  gravite_niveau1:
    display: "Facture de gravité"
    value: 0
    result: "Facture de gravité"
  gravite_niveau2:
    display: "Facture de gravité"
    value: 0
    result: "Facture de gravité"
  pronostic:
    display: "Facteur pronostic"
    value: 0
    result: "Facteur pronostic"

# Website header
header:
 title:    "Aide à l'auto-diagnostic pour COVID19"
 logo:     ""
 color:    "is-primary" 
 subtitle: "En cas de doute, consultez un médecin ou appelez le [15](tel:15)."

# Website footer
footer:
 text:    "Site en version alpha."
 contact:  "Une adresse email"

# Mandatory configuration option
tree:
  - name:       "0"  
    text:       "Un titre pour la page d'accueil"
    home-page:  true
    force-help: true
    no-summary: true
    help:       "Un texte d'introduction ici."
    choices:
    - answer: "Commencez à s'auto-diagnotiquer"
      goto:   "1"
      color:  "is-info"

  - name:       "1"
    text:       "Pensez-vous avoir eu de la fièvre ces derniers jours (frissons, sueurs) ?"
    help:       ""
    start-page: true
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        fievre:
          value: 1
      goto:    "1bis"
      color:   "is-info"
    - answer:  "Non"
      color:   "is-warning"
      goto:    "2"
    - answer:  "Je ne sais pas"
      color:   "is-warning"
      goto:    "2"
      score:
        fievre:
          value: 1

  - name:       "1bis"
    text:       "Quelle est votre température ?"
    help:       ""
    no-summary: true
    choices:
    - answer:  "**Inférieure** ou égale à 35,4°C"
      score:
        gravite_niveau2:
          value: 1
      goto:    "2"
      color:   "is-info"
    - answer:  "**Supérieure** ou égale à 39°C"
      score:
        gravite_niveau1:
          value: 1
      goto:    "2"
      color:   "is-info"
    - answer:  "Entre 35,5 et 37,7°C"
      goto:    "2"
      color:   "is-info"
    - answer:  "Entre 37,8 et 38,9°C"
      goto:    "2"
      color:   "is-info"
      
  - name:    "2"
    text:    "Avez-vous une toux ou une augmentation de votre toux habituelle ces derniers jours ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        toux:
          value: 1
      goto:    "3"
      color:   "is-info"
    - answer:  "Non"
      goto:    "3"
      color:   "is-info"

  - name:    "3"
    text:    "Avez-vous des douleurs musculaires ou des courbatures inhabituelles ces derniers jours ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        courbatures:
          value: 1
      goto:    "4"
      color:   "is-info"
    - answer:  "Non"
      goto:    "4"
      color:   "is-info"

  - name:    "4"
    text:    "Avez-vous un mal de gorge apparu ces derniers jours ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        mal_de_gorge:
          value: 1
      goto:    "5"
      color:   "is-info"
    - answer:  "Non"
      goto:    "5"
      color:   "is-info"
      
  - name:    "5"
    text:    "Avez-vous de la diarrhée ces dernièrs 24 heures (au moins 3 selles molles) ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        diarrhees:
          value: 1
      goto:    "6"
      color:   "is-info"
    - answer:  "Non"
      goto:    "6"
      color:   "is-info"

  - name:    "6"
    text:    "Avez-vous une fatigue inhabituelle ces derniers jours ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "61"
      color:   "is-info"
    - answer:  "Non"
      goto:    "7"
      color:   "is-info"

  - name:    "61"
    text:    "cette fatigue vous oblige-t-elle à vous reposer plus de la moitié de la journée ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        gravite_niveau1:
          value: 1
      goto:    "7"
      color:   "is-info"
    - answer:  "Non"
      goto:    "7"
      color:   "is-info"

  - name:    "7"
    text:    "Avez-vous des difficultés importantes pour vous alimenter ou boire depuis plus de 24h ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        gravite_niveau2:
          value: 1
      goto:    "8"
      color:   "is-info"
    - answer:  "Non"
      goto:    "8"
      color:   "is-info"

  - name:    "8"
    text:    "Avez-vous vu apparaître une gêne respiratoire<br/> ou une augmentation de votre gêne respiratoire habituelle ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      score:
        gravite_niveau2:
          value: 1
      goto:    "9"
      color:   "is-info"
    - answer:  "Non"
      goto:    "9"
      color:   "is-info"

  - name:    "9"
    text:    "Comment vous sentez-vous ?"
    no-summary: true
    choices:
    - answer:  "Bien"
      goto:    "10"
      color:   "is-info"
    - answer:  "Pas bien"
      goto:    "10"
      color:   "is-info"
    - answer:  "Mal"
      goto:    "10"
      color:   "is-info"
      score:
        gravite:
          value: 1

  - name:    "10"
    text:    "Quel est votre âge ?"
    no-summary: true
    choices:
    - answer:  "Moins de 15 ans"
      summary: "Prenez contact avec votre médecin généraliste au moindre doute. Cette application n’est pour l’instant pas adaptée aux personnes de moins de 15 ans. En cas d’urgence, appeler le [15](tel:15)."
      goto:    "moins15ans"
      color:   "is-info"
    - answer:  "Entre 15 et 50 ans"
      goto:    "11"
      color:   "is-info"
    - answer:  "Entre 50 et 69 ans"
      goto:    "11"
      color:   "is-info"
    - answer:  "Supérieur ou égal 70 ans"
      goto:    "11"
      color:   "is-info"
      score:
        pronostic:
          value: 1

  - name:    "11"
    text:    "Quel est votre poids ? Quelle est votre taille ?"
    no-summary: true
    choices:
    - answer:  "IMC supérieure ou égal à 30 kg/m2"
      goto:    "12"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "IMC inférieur ou égal à 30 kg/m2"
      goto:    "12"
      color:   "is-info"

  - name:    "12"
    text:    "Avez-vous de l’hypertension artérielle ou une maladie cardiaque ou vasculaire ?<br/>Ou prenez-vous un traitement à visée cardiologique ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "13"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "13"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      goto:    "13"
      color:   "is-info"
      score:
        pronostic:
          value: 1
      
  - name:    "13"
    text:    "Êtes-vous diabétique ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "14"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "14"
      color:   "is-info"

  - name:    "14"
    text:    "Avez-vous ou avez-vous eu un cancer ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "15"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "15"
      color:   "is-info"

  - name:    "15"
    text:    "Avez-vous une sensation générale de malaise ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "16"
      color:   "is-info"
      score:
        gravite_niveau1:
          value: 1
    - answer:  "Non"
      goto:    "16"
      color:   "is-info"
      
  - name:    "16"
    text:    "Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un pneumologue ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "17"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "17"
      color:   "is-info"

  - name:    "17"
    text:    "Avez-vous une insuffisance rénale chronique dialysée ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "18"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "18"
      color:   "is-info"

  - name:    "18"
    text:    "Avez-vous une maladie chronique du foie ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "19"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "19"
      color:   "is-info"

  - name:    "19"
    text:    "Êtes-vous enceinte ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "20"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "20"
      color:   "is-info"
    - answer:  "Non applicable"
      goto:    "20"
      color:   "is-info"

  - name:    "20"
    text:    "Avez-vous une maladie connue pour diminuer vos défenses immunitaires ?"
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "21"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "21"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      goto:    "21"
      color:   "is-info"
      score:
        pronostic:
          value: 1

  - name:    "21"
    text:    "Prenez-vous un traitement immunosuppresseur ?"
    help: "C’est un traitement qui diminue vos défenses contre les infections. Voici quelques exemples : corticoïdes, méthotrexate, ciclosporine, tacrolimus, azathioprine, cyclophosphamide (liste non exhaustive)."
    no-summary: true
    choices:
    - answer:  "Oui"
      goto:    "fin"
      color:   "is-info"
      score:
        pronostic:
          value: 1
    - answer:  "Non"
      goto:    "fin"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      goto:    "fin"
      color:   "is-info"
      score:
        pronostic:
          value: 1

  - name: "moins15ans"
    text: "Vous avez moins de quinze ans."
    done: true

  - name: "fin"
    text: "Merci de vous être auto-diagnostiqué"
    done: true
