# Default locale for UI strings
locale: "fr"

# Customize UI strings
ui-strings:
  # display-help:         "Display help"
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # mail-body-default:    "Here is my feedback:\n"
  # redo:                 "Redo"
  # ok:                   "Okay"
  contact-intro:        "Vos remarques : mobilisation-covid@sante.gouv.fr"
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
 title:    "Démonstrateur de l'algorithme d'orientation COVID19"
 logo:     "https://solidarites-sante.gouv.fr/IMG/siteon0.jpg"
 color:    "is-primary"
 subtitle: "Ce site sert de documentation pour l'implémentation de l'algorithme d'orientation COVID19.  Pour plus d'informations, reportez-vous à la [page principale](https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/)."

# Website footer
footer:
 text:    "Démonstration de l'algorithme d'orientation COVID-19."
 contact:  ""

# Allow users to send you emails with the summary?
mail-to: "mobilisation-covid@sante.gouv.fr"

# Display help along with questions by default?
display-help: true

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
display-score-details: true

# Only the score with the highest value?
display-score-top-result: true

# Some text message to always display after the score results
display-unconditionally: "Restez chez vous au maximum en attendant que les symptômes disparaissent. Prenez votre température deux fois par jour. Rappel des mesures d’hygiène. Un dispositif national grand public de soutien psychologique au bénéfice des personnes qui en auraient besoin est accessible via le numéro vert: 0 800 130 000."

# Set initial variables to register scores.  Each entry of
# score-variables start with the name of the variable (you can pick
# up any yaml-acceptable name), then:
#
# (1) "display": what to display when detailed scores are displayed
# (2) "value": the initial value of the variable
# (3) "as-top-result-display": what to display when the variable is
#      the one with the highest score when the user is done.
score-variables:
  moins-de-15-ans:
    doc: "Si la personne a strictement moins de 15 ans."
    display: "Moins de 15 ans"
    value: 0
  plus-de-50-ans:
    doc: "Si la personne a strictement plus de 49 ans."
    display: "Plus de 49 ans"
    value: 0
  poids:
    doc: "Le poids en kilogrammes."
    display: "Poids"
    value: 0
  taille:
    doc: "La taille en mètre."
    display: "Taille"
    value: 0
  fievre:
    doc: "Indicateur de fièvre."
    display: "Fièvre"
    value: 0
  toux:
    doc: "Indicateur de toux."
    display: "Toux"
    value: 0
  anosmie:
    doc: "Si la personne a indiqué un trouble du goût ou de l'odorat."
    display: "Trouble goût/odorat"
    value: 0
  douleurs:
    doc: "Si la personne a indiqué avoir eu mal à la gorge ou des douleurs musculaires ou des courbatures."
    display: "Douleurs"
    value: 0
  diarrhees:
    doc: "Si la personne a indiqué des diarrhées."
    display: "Diarrhées"
    value: 0
  facteurs-gravite-mineurs:
    doc: "Facteurs de gravité mineurs."
    display: "Facteurs de gravité mineurs"
    value: 0
  facteurs-gravite-majeurs:
    doc: "Facteurs de gravité majeurs."
    display: "Facteurs de gravité majeurs"
    value: 0
  facteurs-pronostique:
    doc: "Facteur pronostique."
    display: "Facteur pronostic"
    value: 0

# Sync with pseudo-code.org:
# Priority 1 -> FIN1
# Priority 6 -> FIN2
# Priority 4 -> FIN3
# Priority 3 -> FIN4
# Priority 2 -> FIN5
# Priority 5 -> FIN6
# Priority 8 -> FIN7
# Priority 7 -> FIN8
# Priority 9 -> FIN9
#
# Set conditional output depending on scores.
# Each entry is composed of the name of the condition (you can pick up
# any yaml-acceptable name), then:
#
# (1) notification (optional): bulma-based class names for the UI notification
# (2) message (mandatory): message to display when one of the condition is met
# (3) anything else is a "condition", which lists variables and their minimal
# values for the condition to be met.
conditional-score-outputs:
  FIN1:
    priority: 1
    message: "Prenez contact avec votre médecin généraliste au moindre doute.<br/>Cette application n’est pour l’instant pas adaptée aux personnes de moins de 15 ans.<br/>En cas d’urgence, appeler le [15](tel:15)."
    notification: "is-danger"
    condition-1:
      moins-de-15-ans: 1
  FIN5:
    priority: 2
    message: "Appelez le [15](tel:15)."
    notification: "is-danger"
    condition-1:
      facteurs-gravite-majeurs: 1
  FIN4:
    priority: 3
    message: "Téléconsultation ou médecin généraliste ou visite à domicile (SOS médecins).<br/>S'il n'est pas possible de joindre un médecin ou d'obtenir une téléconsultation, appelez le [15](tel:15)."
    notification: "is-danger"
    condition-1:
      facteurs-gravite-mineurs: 2
      facteurs-pronostique: 1
      fievre: 1
      toux: 1
    condition-2:
      facteurs-gravite-mineurs: 2
      facteurs-pronostique: 1
      fievre: 1
      douleurs: 1
    condition-3:
      facteurs-gravite-mineurs: 2
      facteurs-pronostique: 1
      toux: 1
      diarrhees: 1
    condition-4:
      facteurs-gravite-mineurs: 2
      facteurs-pronostique: 1
      toux: 1
      anosmie: 1
  FIN3:
    priority: 4
    notification: "is-warning"
    message: "Téléconsultation ou médecin généraliste ou visite à domicile (SOS médecins).<br/>Appelez le [15](tel:15) si une gêne respiratoire ou des difficultés importantes pour vous alimenter ou boire pendant plus de 24 heures apparaissent."
    condition-1:
      fievre: 1
      toux: 0
      diarrhees: 1
      plus-de-50-ans: 1
    condition-2:
      fievre: 1
      toux: 0
      douleurs: 1
      plus-de-50-ans: 1
    condition-3:
      fievre: 1
      toux: 0
      anosmie: 1
      plus-de-50-ans: 1
    condition-4:
      fievre: 1
      toux: 0
      diarrhees: 1
      plus-de-50-ans: 1
    condition-5:
      fievre: 1
      toux: 0
      diarrhees: 1
      facteurs-gravite-mineurs: 1
    condition-6:
      fievre: 1
      toux: 0
      douleurs: 1
      facteurs-gravite-mineurs: 1
    condition-7:
      fievre: 1
      toux: 0
      anosmie: 1
      facteurs-gravite-mineurs: 1
    condition-8:
      fievre: 1
      toux: 0
      diarrhees: 1
      facteurs-gravite-mineurs: 1
  FIN6:
    priority: 5
    message: "Téléconsultation ou médecin généraliste ou visite à domicile (SOS médecins)."
    notification: "is-warning"
    condition-1:
      fievre: 1
      toux: 1
  FIN2:
    priority: 6
    message: "Nous vous conseillons de rester à votre domicile et de contacter votre médecin en cas d'apparition de nouveaux symptômes.<br/>Vous pourrez aussi utiliser à nouveau l'application pour réévaluer vos symptômes."
    notification: "is-warning"
    condition-1:
      fievre: 1
      toux: 0
      facteurs-gravite-mineurs: 0
      facteurs-pronostique: 0
      plus-de-50-ans: 0
      diarrhees: 1
    condition-2:
      fievre: 1
      toux: 0
      facteurs-gravite-mineurs: 0
      facteurs-pronostique: 0
      plus-de-50-ans: 0
      douleurs: 1
    condition-1:
      fievre: 1
      toux: 0
      facteurs-gravite-mineurs: 0
      facteurs-pronostique: 0
      plus-de-50-ans: 0
      anosmie: 1
  FIN8:
    priority: 7
    notification: "is-warning"
    message: "Votre situation ne relève probablement pas du Covid-19.<br/>Un avis médical est recommandé. Au moindre doute, appelez le [15](tel:15)."
    condition-1:
      toux: 1
      douleurs: 0
      fievre: 0
      anosmie: 0
      facteurs-gravite-mineurs: 1
    condition-2:
      douleurs: 1
      toux: 0
      anosmie: 0
      fievre: 0
      facteurs-gravite-mineurs: 1
    condition-3:
      anosmie: 1
      douleurs: 0
      toux: 0
      fievre: 0
      facteurs-gravite-mineurs: 1
    condition-4:
      toux: 1
      anosmie: 0
      douleurs: 0
      fievre: 0
      facteurs-pronostique: 1
    condition-5:
      toux: 0
      anosmie: 0
      douleurs: 1
      fievre: 0
      facteurs-pronostique: 1
    condition-6:
      anosmie: 1
      toux: 0
      douleurs: 0
      fievre: 0
      facteurs-pronostique: 1
  FIN7:
    priority: 8
    notification: "is-info"
    message: "Votre situation ne relève probablement pas du Covid-19.<br/>Consultez votre médecin au moindre doute.<br/>Si de nouveaux symptomes apparaissent, refaites le test."
    condition-1:
      toux: 1
      anosmie: 0
      douleurs: 0
      fievre: 0
      facteurs-gravite-mineurs: 0
    condition-2:
      douleurs: 1
      toux: 0
      anosmie: 0
      fievre: 0
      facteurs-gravite-mineurs: 0
    condition-3:
      anosmie: 1
      toux: 0
      douleurs: 0
      fievre: 0
      facteurs-gravite-mineurs: 0
  FIN9:
    priority: 9
    notification: "is-success"
    message: "Votre situation ne relève probablement pas du Covid-19. N’hésitez pas à contacter votre médecin en cas de doute.<br/>Vous pouvez refaire le test en cas de nouveau symptôme pour réévaluer la situation.<br/>Pour toute information concernant le Covid-19, composer le 0 800 130 000."
    condition-1:
      toux: 0
      fievre: 0
      douleurs: 0
      anosmie: 0

# Mandatory configuration option
# FIXME: complete documentation
tree:
  - node:       "0"
    text:       "COVID19: Algorithme d'orientation - site de démonstration"
    home-page:  true
    force-help: true
    help:       "Ce site est un site de **démonstration** pour l'algorithme d'orientation COVID-19.  Aucune donnée n'est collectée."
    choices:
    - answer: "Démarrer"
      goto:   "1.1"
      color:  "is-info"

  - node:       "1.1"
    progress:   "[1 23]"
    text:       "Pensez-vous avoir eu de la fièvre ces derniers jours (frissons, sueurs) ?"
    start-page: true
    choices:
    - answer:  "Oui"
      score:
        fievre:
          value: 1
      goto:    "1.1.1"
      color:   "is-info"
    - answer:  "Non"
      color:   "is-info"
      goto:    "1.2"
    - answer:  "Je ne sais pas"
      color:   "is-info"
      goto:    "1.2"
      score:
        fievre:
          value: 1

  - node:       "1.1.1"
    progress:   "[2 23]"
    text:       "Quelle est votre température ?"
    choices:
    - answer:  "**Inférieure** ou égale à 35,4°C"
      goto:    "1.2"
      color:   "is-info"
    - answer:  "Entre 35,5 et 37,7°C"
      goto:    "1.2"
      color:   "is-info"
    - answer:  "Entre 37,8 et 38,9°C"
      goto:    "1.2"
      color:   "is-info"
    - answer:  "**Supérieure** ou égale à 39°C"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.2"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.2"
      color:   "is-info"

  - node:    "1.2"
    progress:   "[3 23]"
    text:    "Avez-vous une toux ou une augmentation de votre toux habituelle ces derniers jours ?"
    choices:
    - answer:  "Oui"
      score:
        toux:
          value: 1
      goto:    "1.3"
      color:   "is-info"
    - answer:  "Non"
      goto:    "1.3"
      color:   "is-info"

  - node:      "1.3"
    progress:   "[4 23]"
    text:      "Avez-vous noté une forte diminution de votre goût ou de l'odorat ces derniers jours ?"
    choices:
    - answer:  "Oui"
      goto:    "1.4"
      color:   "is-info"
      score:
        anosmie:
          value: 1
    - answer:  "Non"
      goto:    "1.4"
      color:   "is-info"

  - node:    "1.4"
    progress:   "[5 23]"
    text:    "Avez-vous un mal de gorge ou des douleurs musculaires<br/>ou des courbatures inhabituelles apparus ces derniers jours ?"
    choices:
    - answer:  "Oui"
      score:
        douleurs:
          value: 1
      goto:    "1.5"
      color:   "is-info"
    - answer:  "Non"
      goto:    "1.5"
      color:   "is-info"

  - node:    "1.5"
    progress:   "[6 23]"
    text:    "Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles molles) ?"
    choices:
    - answer:  "Oui"
      score:
        diarrhees:
          value: 1
      goto:    "1.6"
      color:   "is-info"
    - answer:  "Non"
      goto:    "1.6"
      color:   "is-info"

  - node:    "1.6"
    progress:   "[7 23]"
    text:    "Avez-vous une fatigue inhabituelle ces derniers jours ?"
    choices:
    - answer:  "Oui"
      goto:    "1.6.1"
      color:   "is-info"
    - answer:  "Non"
      goto:    "1.7"
      color:   "is-info"

  - node:    "1.6.1"
    progress:   "[8 23]"
    text:    "Cette fatigue vous oblige-t-elle à vous reposer plus de la moitié de la journée ?"
    choices:
    - answer:  "Oui"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.7"
      color:   "is-info"
    - answer:  "Non"
      goto:    "1.7"
      color:   "is-info"

  - node:    "1.7"
    progress:   "[9 23]"
    text:    "Êtes-vous dans l'impossibilité de vous alimenter ou boire DEPUIS 24 HEURES OU PLUS ?"
    choices:
    - answer:  "Oui"
      score:
        facteurs-gravite-majeurs:
          value: 1
      goto:    "1.8"
      color:   "is-info"
    - answer:  "Non"
      goto:    "1.8"
      color:   "is-info"

  - node:    "1.8"
    progress:   "[10 23]"
    text:    "Dans les dernières 24 heures, avez-vous noté un manque de souffle INHABITUEL<br/>lorsque vous parlez ou faites un petit effort ?"
    choices:
    - answer:  "Oui"
      score:
        facteurs-gravite-majeurs:
          value: 1
      goto:    "2.1"
      color:   "is-info"
    - answer:  "Non"
      goto:    "2.1"
      color:   "is-info"

  - node:    "2.1"
    progress:   "[11 23]"
    text:    "Quel est votre âge ?"
    choices:
    - answer:  "Moins de 15 ans"
      goto:    "2.2"
      score:
        moins-de-15-ans:
          value: 1
      color:   "is-info"
    - answer:  "Entre 15 et 49 ans"
      goto:    "2.2"
      color:   "is-info"
    - answer:  "Entre 50 et 69 ans"
      score:
        plus-de-50-ans:
          value: 1
      goto:    "2.2"
      color:   "is-info"
    - answer:  "70 ans ou plus"
      goto:    "2.2"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
        plus-de-50-ans:
          value: 1

  - node:    "2.2"
    progress:   "[12 23]"
    text:    "Quel est votre poids en kilogrammes ?"
    help: "**Note aux développeurs:** demandez la saisie du poids exact."
    choices:
    - answer:  "<60"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 60
    - answer:  "60-70"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 70
    - answer:  "70-80"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 80
    - answer:  "80-90"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 90
    - answer:  "90-100"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 100
    - answer:  ">100"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 110

  - node:    "2.3"
    progress:   "[13 23]"
    text:    "Quelle est votre taille en mètres ?"
    help: "**Note aux développeurs:** demandez la saisie de la taille exacte."
    choices:
    - answer:  "<1m50"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.40
    - answer:  "1m50-1m60"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.50
    - answer:  "1m60-1m70"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.60
    - answer:  "1m70-1m80"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.70
    - answer:  "1m80-1m90"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.80
    - answer:  ">1m90"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.90

  - node:    "2.4"
    progress:   "[14 23]"
    text:    "Avez-vous une tension artérielle mal équilibrée ?</br>Ou une maladie cardiaque ou vasculaire ?<br/>Ou prenez-vous un traitement à visée cardiologique ?"
    choices:
    - answer:  "Oui"
      goto:    "2.5"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.5"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      goto:    "2.5"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1

  - node:    "2.5"
    progress:   "[15 23]"
    text:    "Êtes-vous diabétique ?"
    choices:
    - answer:  "Oui"
      goto:    "2.6"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.6"
      color:   "is-info"

  - node:    "2.6"
    progress:   "[16 23]"
    text:    "Avez-vous ou avez-vous eu un cancer ?"
    choices:
    - answer:  "Oui"
      goto:    "2.7"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.7"
      color:   "is-info"

  - node:    "2.7"
    progress:   "[17 23]"
    text:    "Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un pneumologue ?"
    choices:
    - answer:  "Oui"
      goto:    "2.8"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.8"
      color:   "is-info"

  - node:    "2.8"
    progress:   "[18 23]"
    text:    "Avez-vous une insuffisance rénale chronique dialysée ?"
    choices:
    - answer:  "Oui"
      goto:    "2.9"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.9"
      color:   "is-info"

  - node:    "2.9"
    progress:   "[19 23]"
    text:    "Avez-vous une maladie chronique du foie ?"
    choices:
    - answer:  "Oui"
      goto:    "2.10"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.10"
      color:   "is-info"

  - node:    "2.10"
    progress:   "[20 23]"
    text:    "Êtes-vous enceinte ?"
    choices:
    - answer:  "Oui"
      goto:    "2.11"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.11"
      color:   "is-info"
    - answer:  "Non applicable"
      goto:    "2.12"
      color:   "is-info"

  - node:    "2.11"
    progress:   "[21 23]"
    text:    "Avez-vous une maladie connue pour diminuer vos défenses immunitaires ?"
    choices:
    - answer:  "Oui"
      goto:    "2.12"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.12"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      goto:    "2.12"
      color:   "is-info"

  - node:    "2.12"
    progress:   "[22 23]"
    text:    "Prenez-vous un traitement immunosuppresseur ?"
    help: "C’est un traitement qui diminue vos défenses contre les infections. Voici quelques exemples : corticoïdes, méthotrexate, ciclosporine, tacrolimus, azathioprine, cyclophosphamide (liste non exhaustive)."
    choices:
    - answer:  "Oui"
      goto:    "fin"
      color:   "is-info"
      score:
        facteurs-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "fin"
      color:   "is-info"
    - answer:  "Je ne sais pas"
      goto:    "fin"
      color:   "is-info"

  - node: "fin-moins-de-15-ans"
    text: "Vous avez moins de quinze ans."
    done: true

  - node: "fin"
    text: "Merci d'avoir utilisé l'algorithme d'orientation COVID-19"
    help: "Cet algorithme est potentiellement modifiable après étude de cas et veille scientifique."
    done: true
