# Default locale for UI strings
locale: "fr"

# Customize UI strings
ui-strings:
  # display-help:         "Display help"
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # redo:                 "Redo"
  # ok:                   "Okay"
  contact-intro:        "Vos remarques : bastien.guerry@data.gouv.fr"
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Allow users to send you emails with the summary?
mail-to: "bastien.guerry@data.gouv.fr"

# Display help along with questions by default?
display-help: true

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
display-score-details: true

# Only the score with the highest value?
display-score-top-result: true

# Set initial variables to register scores.  Each entry of
# score-variables start with the name of the variable (you can pick
# up any yaml-acceptable name), then:
#
# (1) "display": what to display when detailed scores are displayed
# (2) "value": the initial value of the variable
# (3) "as-top-result-display": what to display when the variable is
#      the one with the highest score when the user is done.
score-variables:
  poids:
    doc: "Le poids en kilogrammes."
    display: "Poids"
    value: 0
    as-top-result-display: "Du poids"
  taille:
    doc: "La taille en mètre."
    display: "Taille"
    value: 0
    as-top-result-display: "Taille"
  fievre:
    doc: "Indicateur de fièvre."
    display: "Fièvre"
    value: 0
    as-top-result-display: "De la fièvre"
  toux:
    doc: "Indicateur de toux."
    display: "Toux"
    value: 0
    as-top-result-display: "De la toux"
  moins15ans:
    doc: "Si la personne a moins de 15 ans."
    display: "Moins de 15 ans"
    value: 0
    as-top-result-display: "Moins de 15 ans"
  plus50ans:
    doc: "Si la personne a plus de 50 ans."
    display: "Plus de 50 ans"
    value: 0
    as-top-result-display: "Plus de 50 ans"
  courbatures:
    doc: "Si la personne a indiqué des courbatures."
    display: "Courbatures"
    value: 0
    as-top-result-display: "Des courbatures"
  mal-de-gorge:
    doc: "Si la personne a indiqué avoir eu mal à la gorge."
    display: "Mal de gorge"
    value: 0
    as-top-result-display: "Mal de gorge"
  diarrhees:
    doc: "Si la personne a indiqué des diarrhées."
    display: "Diarrhées"
    value: 0
    as-top-result-display: "Diarrhées"
  facteurs-gravite-mineurs:
    doc: "Facteurs de gravité mineurs."
    display: "Gravité niveau 1"
    value: 0
    as-top-result-display: "Gravité niveau 1"
  facteurs-gravite-majeurs:
    doc: "Facteurs de gravité majeurs."
    display: "Gravité niveau 2"
    value: 0
    as-top-result-display: "Gravité niveau 2"
  facteur-pronostique:
    doc: "Facteur pronostique."
    display: "Facteur pronostic"
    value: 0
    as-top-result-display: "Facteur pronostic"

# Set conditional output depending on scores.
# Each entry is composed of the name of the condition (you can pick up
# any yaml-acceptable name), then:
#
# (1) notification (optional): bulma-based class names for the UI notification
# (2) message (mandatory): message to display when one of the condition is met
# (3) anything else is a "condition", which lists variables and their minimal
# values for the condition to be met.
#
conditional-score-outputs:
  ras:
    notification: "is-success"
    message: "Votre situation ne relève probablement pas du Covid-19. N’hésitez pas à contacter votre médecin en cas de doute. Vous pouvez refaire le test en cas de nouveau symptôme pour réévaluer la situation. Pour toute information concernant le Covid-19, composer le 0 800 130 000."
    condition-1:
      toux: 0
      fievre: 0
      mal-de-gorge: 0
      courbatures: 0
  no-gravite-one-symptom:
    notification: "is-success"
    message: "Votre situation ne relève probablement pas du Covid-19. Consultez votre médecin au moindre doute."
    condition-1:
      toux: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
    condition-2:
      fievre: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
    condition-3:
      mal-de-gorge: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
    condition-4:
      courbatures: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
  no-pronostic-no-gravite-symptoms-inf50:
    notification: "is-info"
    message: "Nous vous conseillons de rester à votre domicile et de contacter votre médecin en cas d’apparition de nouveaux symptômes. Vous pourrez aussi utiliser à nouveau l’application pour réévaluer vos symptômes."
    condition-1:
      facteur-pronostique: 0
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
      plus50ans: 0
  gravite-niveau-1-symptom:
    notification: "is-warning"
    message: "Votre situation ne relève probablement pas du Covid-19. Un avis médical est recommandé. Au moindre doute, appelez le 15."
    condition-1:
      toux: 1
      facteurs-gravite-mineurs: 1
    condition-2:
      fievre: 1
      facteurs-gravite-mineurs: 1
    condition-3:
      mal-de-gorge: 1
      facteurs-gravite-mineurs: 1
    condition-4:
      courbatures: 1
      facteurs-gravite-mineurs: 1
  no-pronostic-no-facteurs-gravite-majeurs-symptoms:
    notification: "is-warning"
    message: "Téléconsultation ou médecin généraliste ou visite à domicile (SOS médecins)"
    condition-1:
      facteur-pronostique: 0
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
      plus50ans: 1
    condition-2:
      facteur-pronostique: 0
      facteurs-gravite-mineurs: 1
      facteurs-gravite-majeurs: 0
      plus50ans: 1
    condition-3:
      facteur-pronostique: 0
      fievre: 1
      toux: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
    condition-4:
      facteur-pronostique: 0
      fievre: 1
      toux: 1
      facteurs-gravite-mineurs: 1
      facteurs-gravite-majeurs: 0
    condition-5:
      facteur-pronostique: 1
      fievre: 1
      toux: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
    condition-6:
      facteur-pronostique: 1
      fievre: 1
      toux: 1
      facteurs-gravite-mineurs: 1
      facteurs-gravite-majeurs: 0
    condition-7:
      facteur-pronostique: 1
      facteurs-gravite-mineurs: 0
      facteurs-gravite-majeurs: 0
    condition-8:
      facteur-pronostique: 1
      facteurs-gravite-mineurs: 1
    condition-9:
      facteur-pronostique: 1
      fievre: 1
      toux: 1
      facteurs-gravite-mineurs: 2
    condition-10:
      facteur-pronostique: 1
      facteurs-gravite-mineurs: 2
  pronostic-gravite-symptoms:
    message: "Appel du 15"
    notification: "is-danger"
    condition-1:
      facteurs-gravite-majeurs: 1
  pronostic-gravite-symptoms:
    message: "Cette application n'est pas l'instant pas adaptée aux personnes de moins de 15 ans."
    notification: "is-danger"
    condition-1:
      moins15ans: 1

# Website header
header:
 title:    "COVID19: Algorithme d'orientation"
 logo:     ""
 color:    "is-primary"
 subtitle: "En cas de doute, consultez un médecin ou appelez le 15."

# Website footer
footer:
 text:    "Site de démonstration de l'algorithme d'orientation pour le COVID-19"
 contact:  ""

# Mandatory configuration option
# FIXME: complete documentation
tree:
  - name:       "0"
    text:       "COVID19: Algorithme d'orientation - site de démonstration"
    home-page:  true
    force-help: true
    help:       "Ce site a pour but d'exposer l'algorithme d'orientation COVID-19"
    choices:
    - answer: "Démarrer"
      goto:   "1.1"
      color:  "is-info"

  - name:       "1.1"
    progress:   "[1 24]"
    text:       "Pensez-vous avoir eu de la fièvre ces derniers jours (frissons, sueurs) ?"
    start-page: true
    choices:
    - answer:  "Oui"
      score:
        fievre:
          value: 1
      goto:    "1.1.1"
      color:   "is-warning"
    - answer:  "Non"
      color:   "is-success"
      goto:    "1.2"
    - answer:  "Je ne sais pas"
      color:   "is-warning"
      goto:    "1.2"
      score:
        fievre:
          value: 1

  - name:       "1.1.1"
    progress:   "[2 25]"
    text:       "Quelle est votre température ?"
    choices:
    - answer:  "**Inférieure** ou égale à 35,4°C"
      goto:    "1.2"
      color:   "is-warning"
    - answer:  "Entre 35,5 et 37,7°C"
      goto:    "1.2"
      color:   "is-success"
    - answer:  "Entre 37,8 et 38,9°C"
      goto:    "1.2"
      color:   "is-warning"
    - answer:  "**Supérieure** ou égale à 39°C"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.2"
      color:   "is-danger"
    - answer:  "Je ne sais pas"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.2"
      color:   "is-danger"

  - name:    "1.2"
    progress:   "[3 24]"
    text:    "Avez-vous une toux ou une augmentation de votre toux habituelle ces derniers jours ?"
    choices:
    - answer:  "Oui"
      score:
        toux:
          value: 1
      goto:    "1.3"
      color:   "is-warning"
    - answer:  "Non"
      goto:    "1.3"
      color:   "is-success"

  - name:      "1.3"
    progress:   "[4 24]"
    text:      "Avez-vous noté une forte diminution de votre goût ou de l'odorat ces derniers jours ?"
    choices:
    - answer:  "Oui"
      goto:    "1.4"
      color:   "is-warning"
    - answer:  "Non"
      goto:    "1.4"
      color:   "is-success"

  - name:    "1.4"
    progress:   "[5 24]"
    text:    "Avez-vous un mal de gorge apparu ces derniers jours ?"
    choices:
    - answer:  "Oui"
      score:
        mal-de-gorge:
          value: 1
      goto:    "1.5"
      color:   "is-warning"
    - answer:  "Non"
      goto:    "1.5"
      color:   "is-success"

  - name:    "1.5"
    progress:   "[6 24]"
    text:    "Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles molles) ?"
    choices:
    - answer:  "Oui"
      score:
        diarrhees:
          value: 1
      goto:    "1.6"
      color:   "is-warning"
    - answer:  "Non"
      goto:    "1.6"
      color:   "is-success"

  - name:    "1.6"
    progress:   "[7 24]"
    text:    "Avez-vous une fatigue inhabituelle ces derniers jours ?"
    choices:
    - answer:  "Oui"
      goto:    "1.6.1"
      color:   "is-warning"
    - answer:  "Non"
      goto:    "1.7"
      color:   "is-success"

  - name:    "1.6.1"
    progress:   "[8 24]"
    text:    "Cette fatigue vous oblige-t-elle à vous reposer plus de la moitié de la journée ?"
    choices:
    - answer:  "Oui"
      score:
        facteurs-gravite-mineurs:
          value: 1
      goto:    "1.7"
      color:   "is-danger"
    - answer:  "Non"
      goto:    "1.7"
      color:   "is-warning"

  - name:    "1.7"
    progress:   "[9 24]"
    text:    "Avez-vous des difficultés importantes pour vous alimenter ou boire depuis plus de 24h ?"
    choices:
    - answer:  "Oui"
      score:
        facteurs-gravite-majeurs:
          value: 1
      goto:    "1.8"
      color:   "is-danger"
    - answer:  "Non"
      goto:    "1.8"
      color:   "is-success"

  - name:    "1.8"
    progress:   "[10 24]"
    text:    "Êtes-vous essoufflé lorsque vous parlez ou faites un petit effort ?"
    choices:
    - answer:  "Oui"
      score:
        facteurs-gravite-majeurs:
          value: 1
      goto:    "2.1"
      color:   "is-danger"
    - answer:  "Non"
      goto:    "2.1"
      color:   "is-success"

  - name:    "2.1"
    progress:   "[11 24]"
    text:    "Quel est votre âge ?"
    choices:
    - answer:  "Moins de 15 ans"
      summary: "Prenez contact avec votre médecin généraliste au moindre doute. En cas d’urgence, appeler le [15](tel:15)."
      goto:    "fin-moins15ans"
      score:
        moins15ans:
          value: 1
      color:   "is-warning"
    - answer:  "Entre 15 et 50 ans"
      goto:    "2.2"
      color:   "is-success"
    - answer:  "Entre 50 et 69 ans"
      score:
        plus50ans:
          value: 1
      goto:    "2.2"
      color:   "is-info"
    - answer:  "70 ans ou plus"
      goto:    "2.2"
      color:   "is-danger"
      score:
        facteur-pronostique:
          value: 1
        plus50ans:
          value: 1

  - name:    "2.2"
    progress:   "[12 24]"
    text:    "Quel est votre poids en kilogrammes ?"
    choices:
    - answer:  "Moins de 60"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 60
    - answer:  "60-70"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 70
    - answer:  "70-80"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 80
    - answer:  "80-90"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 90
    - answer:  "90-100"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 100
    - answer:  "Plus de 100"
      goto:    "2.3"
      color:   "is-info"
      score:
        poids:
          value: 110

  - name:    "2.3"
    progress:   "[13 24]"
    text:    "Quelle est votre taille en mètre ?"
    choices:
    - answer:  "Moins de 1m50"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.40
    - answer:  "1m50-1m60"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.50
    - answer:  "1m60-1m70"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.60
    - answer:  "1m70-1m80"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.70
    - answer:  "1m80-1m90"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.80
    - answer:  "Plus de 1m90"
      goto:    "2.4"
      color:   "is-info"
      score:
        taille:
          value: 1.90

  - name:    "2.4"
    progress:   "[14 24]"
    text:    "Avez-vous une tension artérielle mal équilibrée ?</br>Ou une maladie cardiaque ou vasculaire ?<br/>Ou prenez-vous un traitement à visée cardiologique ?"
    choices:
    - answer:  "Oui"
      goto:    "2.5"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.5"
      color:   "is-success"
    - answer:  "Je ne sais pas"
      goto:    "2.5"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1

  - name:    "2.5"
    progress:   "[15 24]"
    text:    "Êtes-vous diabétique ?"
    choices:
    - answer:  "Oui"
      goto:    "2.6"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.6"
      color:   "is-success"

  - name:    "2.6"
    progress:   "[16 24]"
    text:    "Avez-vous ou avez-vous eu un cancer ?"
    choices:
    - answer:  "Oui"
      goto:    "2.7"
      color:   "is-danger"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.7"
      color:   "is-success"

  - name:    "2.7"
    progress:   "[17 24]"
    text:    "Avez-vous une sensation générale de malaise ?"
    choices:
    - answer:  "Oui"
      goto:    "2.8"
      color:   "is-warning"
      score:
        facteurs-gravite-mineurs:
          value: 1
    - answer:  "Non"
      goto:    "2.8"
      color:   "is-success"

  - name:    "2.8"
    progress:   "[18 24]"
    text:    "Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un pneumologue ?"
    choices:
    - answer:  "Oui"
      goto:    "2.9"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.9"
      color:   "is-success"

  - name:    "2.9"
    progress:   "[19 24]"
    text:    "Avez-vous une insuffisance rénale chronique dialysée ?"
    choices:
    - answer:  "Oui"
      goto:    "2.10"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.10"
      color:   "is-success"

  - name:    "2.10"
    progress:   "[20 24]"
    text:    "Avez-vous une maladie chronique du foie ?"
    choices:
    - answer:  "Oui"
      goto:    "2.11"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.11"
      color:   "is-success"

  - name:    "2.11"
    progress:   "[21 24]"
    text:    "Êtes-vous enceinte ?"
    choices:
    - answer:  "Oui"
      goto:    "2.12"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.12"
      color:   "is-success"
    - answer:  "Non applicable"
      goto:    "2.12"
      color:   "is-info"

  - name:    "2.12"
    progress:   "[22 24]"
    text:    "Avez-vous une maladie connue pour diminuer vos défenses immunitaires ?"
    choices:
    - answer:  "Oui"
      goto:    "2.13"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "2.13"
      color:   "is-success"
    - answer:  "Je ne sais pas"
      goto:    "2.13"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1

  - name:    "2.13"
    progress:   "[23 24]"
    text:    "Prenez-vous un traitement immunosuppresseur ?"
    help: "C’est un traitement qui diminue vos défenses contre les infections. Voici quelques exemples : corticoïdes, méthotrexate, ciclosporine, tacrolimus, azathioprine, cyclophosphamide (liste non exhaustive)."
    choices:
    - answer:  "Oui"
      goto:    "fin"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1
    - answer:  "Non"
      goto:    "fin"
      color:   "is-success"
    - answer:  "Je ne sais pas"
      goto:    "fin"
      color:   "is-warning"
      score:
        facteur-pronostique:
          value: 1

  - name: "fin-moins15ans"
    text: "Vous avez moins de quinze ans."
    done: true

  - name: "fin"
    text: "Merci d'avoir parcouru l'algorithme d'orientation COVID-19"
    help: "Algorithme potentiellement modifiable après étude de cas et veille scientifique."
    done: true
